

export const GET_GROUNDS ='GET_GROUNDS';
export const GET_GROUNDS_SUCCESS ='GET_GROUNDS_SUCCESS';
export const GET_GROUNDS_ERROR ='GET_GROUNDS_ERROR';

export const FILTER_GROUNDS ='FILTER_GROUNDS';
export const FILTER_GROUNDS_SUCCESS ='FILTER_GROUNDS_SUCCESS';
export const FILTER_GROUNDS_ERROR ='FILTER_GROUNDS_ERROR';


export const SEARCH_GROUNDS ='SEARCH_GROUNDS';
export const SEARCH_GROUNDS_SUCCESS ='SEARCH_GROUNDS_SUCCESS';
export const SEARCH_GROUNDS_ERROR  ='SEARCH_GROUNDS_ERROR ';

export const SORT_GROUNDS='SORT_GROUNDS';
export const SORT_GROUNDS_SUCCESS='SORT_GROUNDS_SUCCESS';
export const SORT_GROUNDS_ERROR ='SORT_GROUNDS_ERROR ';



