
export const GET_GROUNDS ='GET_GROUNDS';
export const GET_GROUNDS_SUCCESS ='GET_GROUNDS_SUCCESS';
export const GET_GROUNDS_ERROR ='GET_GROUNDS_ERROR';

export const FILTER_GROUNDS ='FILTER_GROUNDS';
export const FILTER_GROUNDS_SUCCESS ='FILTER_GROUNDS_SUCCESS';
export const FILTER_GROUNDS_ERROR ='FILTER_GROUNDS_ERROR';

export const SEARCH_GROUNDS ='SEARCH_GROUNDS';
export const SEARCH_GROUNDS_SUCCESS ='SEARCH_GROUNDS_SUCCESS';
export const SEARCH_GROUNDS_ERROR  ='SEARCH_GROUNDS_ERROR ';

export const NAME_SORT="NAME_SORT";
export const NAME_SORT_SUCCESS="NAME_SORT_SUCCESS";
export const NAME_SORT_ERROR="NAME_SORT_ERROR";

export const PRICE_SORT="PRICE_SORT";
export const PRICE_SORT_SUCCESS="PRICE_SORT_SUCCESS";
export const PRICE_SORT_ERROR="PRICE_SORT_ERROR";





