export const FETCHING_GROUNDS = "FETCHING_GROUNDS"
export const SUCCESS_GROUNDS = "SUCCESS_GROUNDS"
export const FAILURE_GROUNDS = "FAILURE_GROUNDS"


export const FETCHING_GROUND = "FETCHING_GROUND"
export const SUCCESS_GROUND = "SUCCESS_GROUND"
export const FAILURE_GROUND = "FAILURE_GROUND"


export const OPEN_NOTIFICATION = "OPEN_NOTIFICATION"
export const CLOSE_NOTIFICATION = "CLOSE_NOTIFICATION"